spring:
  application:
    name: itoken-zuul
  zipkin:
    base-url: http://192.168.74.128:9411
  boot:
    admin:
      client:
        url: http://192.168.74.128:8084
server:
  port: 8769
eureka:
  client:
    service-url:
      defaultZone: http://192.168.74.128:8761/eureka/,http://192.168.74.128:8760/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: hello-spring-cloud-web-ribbon
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-web-feign

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info