spring:
  application:
    name: itoken-admin
  zipkin:
    base-url: http://192.168.74.128:9411

server:
  port: 8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.74.128:8761/eureka/,http://192.168.74.128:8760/eureka/