spring:
  application:
    name: itoken-eureka
  zipkin:
    base-url: http://192.168.74.128:9411
  boot:
    admin:
      client:
        url: http://192.168.74.128:8084
server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.74.128
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8760/eureka/,http://${eureka.instance.hostname}:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info