spring:
  application:
    name: itoken-zipkin
  boot:
    admin:
      client:
        url: http://192.168.74.128:8084

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.74.128:8761/eureka/


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info